name: Code Quality Diagnostics

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'PHP: ${{ matrix.php }} Contao: ${{ matrix.contao }}'
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3', '8.4', '8.5' ]
        contao: [ '~5.3.0', '~5.7.0' ]
        phpcq_install: [ 'update' ]
        output: [ '-o github-action -o default' ]

    steps:
      - name: Pull source
        uses: actions/checkout@v6

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      # setup caches
      - name: Cache composer cache directory
        uses: actions/cache@v5
        env:
          cache-name: composer-cache-dir
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}

      - name: Cache vendor directory
        uses: actions/cache@v5
        env:
          cache-name: vendor
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.contao }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-${{ matrix.contao }}-build-${{ env.cache-name }}-

      - name: Cache phpcq directory
        uses: actions/cache@v5
        env:
          cache-name: phpcq
        with:
          path: .phpcq
          key: ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/.phpcq.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}-

      # install dependencies and tools
      - name: Install composer dependencies
        run: |
          composer require contao/core-bundle ${{ matrix.contao }} --no-update
          composer install

      - name: Install phpcq toolchain
        run: ./vendor/bin/phpcq ${{ matrix.phpcq_install }} -v

      # run tests
      - name: Run tests
        run: ./vendor/bin/phpcq run -v ${{ matrix.output }}

      - name: Upload build directory to artifact
        uses: actions/upload-artifact@v6
        if: ${{ success() || failure() }}
        with:
          name: phpcq-builds-php-${{ matrix.php }}-${{ matrix.contao }}
          path: .phpcq/build/
